/**
 * MermaidBlock — renders a Mermaid diagram definition as an inline SVG.
 *
 * Uses dynamic import so the ~300KB mermaid library is only loaded when
 * the AI actually produces a diagram. Renders are sandboxed per-block
 * using unique IDs to avoid collisions when multiple diagrams appear.
 */
import { useEffect, useRef, useState, useCallback } from 'react';
import { X, ZoomIn, ZoomOut, RotateCcw, Maximize2 } from 'lucide-react';

let mermaidInitialized = false;

/** Lazily load + initialize mermaid once. */
async function getMermaid() {
  const { default: mermaid } = await import('mermaid');
  if (!mermaidInitialized) {
    mermaid.initialize({
      startOnLoad: false,
      theme: 'dark',
      themeVariables: {
        primaryColor: '#6d9e37',
        primaryTextColor: '#e0e0e0',
        primaryBorderColor: '#6d9e37',
        lineColor: '#888',
        secondaryColor: '#2a2a2a',
        tertiaryColor: '#1a1a1a',
        fontFamily: 'ui-monospace, monospace',
        fontSize: '13px',
      },
      flowchart: { curve: 'basis', padding: 12 },
      securityLevel: 'loose',
    });
    mermaidInitialized = true;
  }
  return mermaid;
}

/**
 * Sanitize Mermaid source so the parser doesn't choke on common issues
 * generated by LLMs (emojis, <br/> tags, unquoted special chars in labels,
 * Gantt-specific syntax problems).
 */
function sanitize(src: string): string {
  let s = src;

  // 1. Strip emojis / non-BMP characters
  s = Array.from(s)
    .filter((ch) => {
      const cp = ch.codePointAt(0) ?? 0;
      if (cp >= 0x1f000 && cp <= 0x1ffff) return false;
      if (cp >= 0x2600 && cp <= 0x27bf) return false;
      if (cp >= 0xfe00 && cp <= 0xfe0f) return false;
      if (cp === 0x200d) return false;
      return true;
    })
    .join('');

  // 2. Normalize <br/> → <br> (Mermaid only supports <br>)
  s = s.replace(/<br\s*\/>/gi, '<br>');

  // 3. Auto-quote node labels that contain special characters.
  //    Matches: ID[unquoted text] where text has (){}#<>
  //    Converts to: ID["quoted text"]
  s = s.replace(/(\b[A-Za-z_][A-Za-z0-9_]*)\[([^\]"]+)\]/g, (_match, id: string, label: string) => {
    if (/[(){}#<>]/.test(label)) {
      return `${id}["${label}"]`;
    }
    return _match;
  });

  // 4. Auto-quote edge labels that contain special characters.
  //    Matches: -->|unquoted text| or -.->|unquoted text|
  s = s.replace(/([-.]+-?>)\|([^|"]+)\|/g, (_match, arrow: string, label: string) => {
    if (/[(){}#<>/]/.test(label)) {
      return `${arrow}|"${label}"|`;
    }
    return _match;
  });

  // 5. Gantt-specific fixes
  //    a) Replace smart quotes/curly quotes with straight quotes
  s = s.replace(/[\u2018\u2019]/g, "'").replace(/[\u201C\u201D]/g, '"');
  //    b) Strip quotes around Gantt section names (Mermaid doesn't allow them)
  s = s.replace(/^(\s*section\s+)"([^"]+)"/gm, '$1$2');
  //    c) Escape apostrophes in Gantt title/section/task names by removing them
  //       (Mermaid parser chokes on unmatched quotes in these contexts)
  s = s.replace(
    /^(\s*title\s+)(.+)$/gm,
    (_m, prefix: string, rest: string) => prefix + rest.replace(/'/g, ''),
  );
  //    d) Remove commas from Gantt task descriptions (confuses the parser
  //       because comma is the field delimiter: "task : id, date, duration")
  s = s.replace(/^(\s+)([^:]+):(.*)/gm, (_m, indent: string, taskName: string, rest: string) => {
    // Only apply to lines that look like Gantt tasks (have date/duration after colon)
    if (/\d{4}-\d{2}-\d{2}|\d+d\b/.test(rest)) {
      const cleanName = taskName.replace(/,/g, ' &');
      return `${indent}${cleanName}:${rest}`;
    }
    return _m;
  });
  //    e) Fix directive lines with erroneous colons (e.g. "dateFormat :X" → "dateFormat X")
  s = s.replace(/^(\s*(?:dateFormat|axisFormat|tickInterval)\s+):(\S)/gm, '$1$2');
  //    f) Replace hyphens in Gantt task IDs (after the colon) with underscores
  //       e.g. "d12-13" → "d12_13" — hyphens in IDs break the parser
  s = s.replace(
    /^(\s+[^:]+:\s*(?:active|done|crit|milestone)(?:,\s*|\s*,\s*))([a-zA-Z][a-zA-Z0-9-]+)(\s*,)/gm,
    (_m, before: string, id: string, after: string) => `${before}${id.replace(/-/g, '_')}${after}`,
  );
  //    g) Wrap task names starting with digits in quotes to prevent parser confusion
  //       e.g. "7-8 Days :crit, gap, 2d" → '"7-8 Days" :crit, gap, 2d'
  s = s.replace(/^(\s+)(\d[^:]*?)\s*(:.*)/gm, (_m, indent: string, name: string, rest: string) => {
    const trimmed = name.trim();
    // Already quoted — skip
    if (trimmed.startsWith('"')) return _m;
    return `${indent}"${trimmed}" ${rest}`;
  });

  return s;
}

let blockCounter = 0;

/* ── Diagram zoom constants ── */
const DIAGRAM_ZOOM_STEP = 0.15;
const DIAGRAM_MIN_ZOOM = 0.3;
const DIAGRAM_MAX_ZOOM = 3.0;
const DIAGRAM_DEFAULT_ZOOM = 1.0;

/** Fullscreen diagram viewer overlay. */
function DiagramViewer({ svgHtml, onClose }: { svgHtml: string; onClose: () => void }) {
  const [zoom, setZoom] = useState(DIAGRAM_DEFAULT_ZOOM);
  const contentRef = useRef<HTMLDivElement>(null);

  const handleZoomIn = useCallback(
    () => setZoom((z) => Math.min(z + DIAGRAM_ZOOM_STEP, DIAGRAM_MAX_ZOOM)),
    [],
  );
  const handleZoomOut = useCallback(
    () => setZoom((z) => Math.max(z - DIAGRAM_ZOOM_STEP, DIAGRAM_MIN_ZOOM)),
    [],
  );
  const handleZoomReset = useCallback(() => setZoom(DIAGRAM_DEFAULT_ZOOM), []);

  useEffect(() => {
    function onKeyDown(e: KeyboardEvent) {
      if (e.key === 'Escape') onClose();
    }
    window.addEventListener('keydown', onKeyDown);
    return () => window.removeEventListener('keydown', onKeyDown);
  }, [onClose]);

  // Inject SVG and remove width constraints so it renders at natural size
  useEffect(() => {
    if (!contentRef.current) return;
    contentRef.current.innerHTML = svgHtml;
    const svgEl = contentRef.current.querySelector('svg');
    if (svgEl) {
      svgEl.style.width = '';
      svgEl.style.maxWidth = 'none';
      svgEl.style.height = 'auto';
      svgEl.style.minWidth = '800px';
    }
  }, [svgHtml]);

  const zoomBtnClass =
    'flex h-8 w-8 items-center justify-center rounded-lg text-white/50 transition-colors hover:bg-white/[0.08] hover:text-white/80 disabled:opacity-30 disabled:cursor-not-allowed';

  return (
    <div className="fixed inset-0 z-50 flex flex-col">
      {/* Backdrop */}
      <button
        className="absolute inset-0 bg-black/90 backdrop-blur-sm"
        onClick={onClose}
        aria-label="Close diagram viewer"
        tabIndex={-1}
      />
      {/* Header */}
      <div className="relative z-10 flex shrink-0 items-center justify-between border-b border-white/[0.06] bg-black/60 px-6 py-3">
        <span className="text-sm font-medium text-white/70">Diagram Viewer</span>
        <div className="flex items-center gap-1">
          <button
            onClick={handleZoomOut}
            className={zoomBtnClass}
            title="Zoom out"
            disabled={zoom <= DIAGRAM_MIN_ZOOM}
            aria-label="Zoom out"
          >
            <ZoomOut className="h-4 w-4" />
          </button>
          <span className="min-w-[3rem] text-center text-xs text-white/40">
            {Math.round(zoom * 100)}%
          </span>
          <button
            onClick={handleZoomIn}
            className={zoomBtnClass}
            title="Zoom in"
            disabled={zoom >= DIAGRAM_MAX_ZOOM}
            aria-label="Zoom in"
          >
            <ZoomIn className="h-4 w-4" />
          </button>
          <button
            onClick={handleZoomReset}
            className={zoomBtnClass}
            title="Reset zoom"
            aria-label="Reset zoom"
          >
            <RotateCcw className="h-3.5 w-3.5" />
          </button>
          <div className="mx-1 h-5 w-px bg-white/10" />
          <button
            onClick={onClose}
            className="flex h-8 w-8 items-center justify-center rounded-lg text-white/50 transition-colors hover:bg-white/[0.08] hover:text-white/80"
            title="Close (Esc)"
            aria-label="Close diagram viewer"
          >
            <X className="h-4 w-4" />
          </button>
        </div>
      </div>

      {/* Scrollable diagram area */}
      <div className="relative z-10 flex-1 overflow-auto p-8">
        <div
          className="mx-auto inline-block origin-top-left transition-transform duration-150 ease-out"
          style={{ zoom }}
        >
          <div ref={contentRef} className="[&_svg]:overflow-visible" />
        </div>
      </div>
    </div>
  );
}

export default function MermaidBlock({ code, blockKey }: { code: string; blockKey: number }) {
  const containerRef = useRef<HTMLDivElement>(null);
  const [error, setError] = useState<string | null>(null);
  const [rendering, setRendering] = useState(true);
  const [isViewerOpen, setIsViewerOpen] = useState(false);
  const [svgHtml, setSvgHtml] = useState<string>('');
  const idRef = useRef(`mermaid-${blockKey}-${++blockCounter}`);

  useEffect(() => {
    let cancelled = false;

    async function render() {
      try {
        const mermaid = await getMermaid();
        // Sanitize emojis/special chars that break Mermaid's parser,
        // then render directly (skip parse() which is overly strict).
        const clean = sanitize(code);
        const { svg } = await mermaid.render(idRef.current, clean);
        if (!cancelled && containerRef.current) {
          containerRef.current.innerHTML = svg;
          setSvgHtml(svg);
          // Make SVG responsive
          const svgEl = containerRef.current.querySelector('svg');
          if (svgEl) {
            svgEl.removeAttribute('height');
            svgEl.style.width = '100%';
            svgEl.style.height = 'auto';
            // Recalculate viewBox to include all rendered elements (e.g. titles
            // that extend beyond the default viewBox boundaries)
            try {
              const bbox = svgEl.getBBox();
              if (bbox.width > 0 && bbox.height > 0) {
                const pad = 16;
                svgEl.setAttribute(
                  'viewBox',
                  `${bbox.x - pad} ${bbox.y - pad} ${bbox.width + pad * 2} ${bbox.height + pad * 2}`,
                );
              }
            } catch {
              // getBBox may throw if SVG is not in the DOM yet
            }
          }
          setRendering(false);
        }
      } catch (err) {
        if (!cancelled) {
          setError(err instanceof Error ? err.message : 'Failed to render diagram');
          setRendering(false);
        }
      }
    }

    render();
    return () => {
      cancelled = true;
    };
  }, [code]);

  if (error) {
    return (
      <div className="bg-bg-elevated my-2 rounded-lg p-3 text-xs">
        <div className="text-status-error mb-1 font-medium">⚠ Diagram error</div>
        <pre className="text-text-muted whitespace-pre-wrap">{code}</pre>
      </div>
    );
  }

  return (
    <>
      <div
        className="group/diagram bg-bg-elevated relative my-3 cursor-zoom-in overflow-x-auto rounded-xl p-4 transition-colors hover:bg-white/[0.04]"
        style={isViewerOpen ? { visibility: 'hidden' as const } : undefined}
        role="button"
        tabIndex={0}
        onClick={() => !rendering && setIsViewerOpen(true)}
        onKeyDown={(e) => {
          if ((e.key === 'Enter' || e.key === ' ') && !rendering) setIsViewerOpen(true);
        }}
        title="Click to expand diagram"
      >
        {rendering && (
          <div className="text-text-muted flex items-center gap-2 text-xs">
            <span className="inline-block h-3 w-3 animate-spin rounded-full border-2 border-current border-t-transparent" />
            Rendering diagram…
          </div>
        )}
        <div
          ref={containerRef}
          className="flex justify-center [&_svg]:max-w-full [&_svg]:overflow-visible"
        />
        {/* Expand indicator on hover */}
        {!rendering && (
          <div className="pointer-events-none absolute top-3 right-3 flex items-center gap-1.5 rounded-lg bg-black/60 px-2.5 py-1.5 text-white/0 opacity-0 backdrop-blur-sm transition-all group-hover/diagram:text-white/70 group-hover/diagram:opacity-100">
            <Maximize2 className="h-3.5 w-3.5" />
            <span className="text-[11px] font-medium">Click to expand</span>
          </div>
        )}
      </div>

      {/* Fullscreen diagram viewer */}
      {isViewerOpen && svgHtml && (
        <DiagramViewer svgHtml={svgHtml} onClose={() => setIsViewerOpen(false)} />
      )}
    </>
  );
}
