/**
 * Shared types for the Cybernus AI chatbot subsystem.
 */

/** Inline agent activity record — displayed inside conversation messages. */
export interface AgentActivityItem {
  /** Agent display name (e.g. "Scout Agent", "Vision Agent"). */
  agent: string;
  /** Tool type being used (e.g. "web_search", "generate_image"). */
  toolType: string;
  /** Short status label (e.g. "Searching the web...", "Generating image..."). */
  label: string;
  /** Current status. */
  status: 'working' | 'done';
  /** SVG icon path (viewBox 0 0 24 24). */
  iconPath: string;
  /** Accent colour for this agent. */
  color: string;
}

/** A single option in a dynamic in-chat form (generated by the AI via `ask_user` tool). */
export interface ChatFormOption {
  /** Unique identifier for this option. */
  id: string;
  /** Display label (e.g. "📸 Photo portrait"). */
  label: string;
  /** Optional short description shown below the label. */
  description?: string;
  /** The text sent as the user's message when this option is selected. */
  value: string;
}

/** An interactive in-chat form attached to an assistant message. */
export interface ChatForm {
  /** The question/prompt displayed above the options. */
  question: string;
  /** Available choices. */
  options: ChatFormOption[];
  /** Whether to show a free-text "Other" input. */
  allowOther: boolean;
  /** The option id that was selected (null = not yet answered). */
  selectedId?: string | null;
  /** Custom text entered via "Other" (null = not used). */
  customValue?: string | null;
}

/** A single message in the chat conversation. */
export interface ChatMessage {
  id: string;
  role: 'user' | 'assistant';
  content: string;
  /** Optional display-only text shown in the UI instead of `content`.
   *  When set, `content` is still sent to the AI but the user sees `displayContent`. */
  displayContent?: string;
  /** When true, the message is sent to the AI but not rendered in the chat UI. */
  hidden?: boolean;
  /** Client-side actions parsed from the assistant's response. */
  actions?: ToolAction[];
  /** Web search phase: 'searching' while running, 'found' when complete (synthesizing). */
  searchStatus?: 'searching' | 'found';
  /** Inline sub-agent activity tracked during generation. */
  agentActivity?: AgentActivityItem[];
  /** Dynamic in-chat form for user interaction (populated by `ask_user` tool). */
  form?: ChatForm;
}

/** A client-side action the assistant can suggest. */
export interface ToolAction {
  type: 'navigate' | 'open_link';
  /** Display label for the action button. */
  label: string;
  /** URL or path to navigate to / open. */
  url: string;
}
